services:
  docker-monitor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}
    container_name: docker-monitor
    restart: unless-stopped
    environment:
      # Load from .env file
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - DAILY_CHECK_TIME=${DAILY_CHECK_TIME:-09:00}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - NOTIFICATION_ENABLED=${NOTIFICATION_ENABLED:-true}
      - INCLUDE_STOPPED_CONTAINERS=${INCLUDE_STOPPED_CONTAINERS:-false}
      - CONTAINER_NAME_FILTER=${CONTAINER_NAME_FILTER:-}
      - TIMEZONE=${TIMEZONE:-UTC}
    volumes:
      # Mount Docker socket to monitor containers
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount logs directory for persistence
      - ./logs:/app/logs
      # Mount .env file for configuration
      - ./.env:/app/.env:ro
    networks:
      - monitoring
    # Default: scheduled daily monitoring
    command: ["python3", "scripts/run_monitor.py", "--scheduled"]

  # Real-time monitoring service (optional)
  docker-monitor-realtime:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}
    container_name: docker-monitor-realtime
    restart: unless-stopped
    environment:
      # Load from .env file
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - NOTIFICATION_ENABLED=${NOTIFICATION_ENABLED:-true}
      - INCLUDE_STOPPED_CONTAINERS=${INCLUDE_STOPPED_CONTAINERS:-false}
      - CONTAINER_NAME_FILTER=${CONTAINER_NAME_FILTER:-}
      - TIMEZONE=${TIMEZONE:-UTC}
      - REALTIME_CHECK_INTERVAL=${REALTIME_CHECK_INTERVAL:-15}
    volumes:
      # Mount Docker socket to monitor containers
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount logs directory for persistence
      - ./logs:/app/logs
      # Mount .env file for configuration
      - ./.env:/app/.env:ro
    networks:
      - monitoring
    # Real-time monitoring every 15 seconds (reduced frequency)
    command: ["python3", "scripts/run_monitor.py", "--realtime", "15"]
    profiles:
      - realtime

networks:
  monitoring:
    driver: bridge